# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{radiant-shop_variants-extension}
  s.version = "0.1.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Dirk Kelly"]
  s.date = %q{2011-03-30}
  s.description = %q{RadiantShop: Create variants of products, with alternative prices}
  s.email = %q{dk@dirkkelly.com}
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    "README",
    "Rakefile",
    "VERSION",
    "app/controllers/admin/shop/products/variant_templates_controller.rb",
    "app/controllers/admin/shop/products/variants_controller.rb",
    "app/controllers/admin/shop/variants_controller.rb",
    "app/models/shop_product_variant.rb",
    "app/models/shop_variant.rb",
    "app/views/admin/shop/products/edit/buttons/_browse_templates.html.haml",
    "app/views/admin/shop/products/edit/buttons/_new_variant.html.haml",
    "app/views/admin/shop/products/edit/parts/_variants.html.haml",
    "app/views/admin/shop/products/edit/popups/_browse_templates.html.haml",
    "app/views/admin/shop/products/edit/popups/_new_variant.html.haml",
    "app/views/admin/shop/products/edit/shared/_variant.html.haml",
    "app/views/admin/shop/products/index/buttons/_variants.html.haml",
    "app/views/admin/shop/variants/edit.html.haml",
    "app/views/admin/shop/variants/edit/_foot.html.haml",
    "app/views/admin/shop/variants/edit/_form.html.haml",
    "app/views/admin/shop/variants/edit/_head.html.haml",
    "app/views/admin/shop/variants/edit/_inputs.html.haml",
    "app/views/admin/shop/variants/edit/_meta.html.haml",
    "app/views/admin/shop/variants/edit/_parts.html.haml",
    "app/views/admin/shop/variants/edit/_popups.html.haml",
    "app/views/admin/shop/variants/edit/inputs/_name.html.haml",
    "app/views/admin/shop/variants/edit/inputs/_options.html.haml",
    "app/views/admin/shop/variants/index.html.haml",
    "app/views/admin/shop/variants/index/_foot.html.haml",
    "app/views/admin/shop/variants/index/_head.html.haml",
    "app/views/admin/shop/variants/index/_variant.html.haml",
    "app/views/admin/shop/variants/index/buttons/_add_variant.html.haml",
    "app/views/admin/shop/variants/index/buttons/_categories.html.haml",
    "app/views/admin/shop/variants/new.html.haml",
    "app/views/admin/shop/variants/remove.html.haml",
    "config/locales/en.yml",
    "config/routes.rb",
    "cucumber.yml",
    "db/migrate/20101015162238_setup_shop_variants.rb",
    "db/migrate/20110330100134_add_position_to_product_variant.rb",
    "features/support/env.rb",
    "features/support/paths.rb",
    "lib/radiant-shop_variants-extension.rb",
    "lib/shop_variants/controllers/products_controller.rb",
    "lib/shop_variants/interface/variants.rb",
    "lib/shop_variants/models/product.rb",
    "lib/shop_variants/tags/helpers.rb",
    "lib/shop_variants/tags/product_variant.rb",
    "lib/tasks/shop_variants_extension_tasks.rake",
    "public/javascripts/admin/extensions/shop/variants/edit.js",
    "public/stylesheets/sass/admin/extensions/shop/variants/edit.sass",
    "radiant-shop_variants-extension.gemspec",
    "shop_variants_extension.rb",
    "spec/controllers/admin/shop/products/variant_templates_controller_spec.rb",
    "spec/controllers/admin/shop/products/variants_controller_spec.rb",
    "spec/controllers/admin/shop/variants_controller_spec.rb",
    "spec/datasets/shop_product_variants.rb",
    "spec/datasets/shop_variants.rb",
    "spec/lib/shop_variants/tags/helpers_spec.rb",
    "spec/lib/shop_variants/tags/product_variant_spec.rb",
    "spec/models/shop_product_spec.rb",
    "spec/models/shop_product_variant_spec.rb",
    "spec/models/shop_variant_spec.rb",
    "spec/spec.opts",
    "spec/spec_helper.rb"
  ]
  s.homepage = %q{https://github.com/thefrontiergroup/radiant-shop_variants-extension}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.4.1}
  s.summary = %q{Shop Variants Extension for Radiant CMS}
  s.test_files = [
    "spec/controllers/admin/shop/products/variant_templates_controller_spec.rb",
    "spec/controllers/admin/shop/products/variants_controller_spec.rb",
    "spec/controllers/admin/shop/variants_controller_spec.rb",
    "spec/datasets/shop_product_variants.rb",
    "spec/datasets/shop_variants.rb",
    "spec/lib/shop_variants/tags/helpers_spec.rb",
    "spec/lib/shop_variants/tags/product_variant_spec.rb",
    "spec/models/shop_product_spec.rb",
    "spec/models/shop_product_variant_spec.rb",
    "spec/models/shop_variant_spec.rb",
    "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<radiant-shop-extension>, [">= 0"])
    else
      s.add_dependency(%q<radiant-shop-extension>, [">= 0"])
    end
  else
    s.add_dependency(%q<radiant-shop-extension>, [">= 0"])
  end
end

